### ISSUE TITLE
Support for event listener options

### ISSUE THREAD

**Issue by heokhe** [donavon/use-event-listener#31]
Can we have something like this?
```js
useEventListener('click', () => {
  console.log('The window is clicked and cannot be clicked anymore');
}, { once: true });
```

**Comment by srmagura** [comment]
Hey @hkh12, my fork [@srmagura/use-event-listener](https://github.com/srmagura/use-event-listener) already supports the other two `addEventListener` options: `capture` and `passive`.

I did not add the `once` option because I don't think it makes sense in the context of hooks. Hooks run after every render so it's a bit weird to have a hook that only does something a single time.

Instead, you can do:
```
useEffect(() => {
    window.addEventListener('click', fn, { once: true })
}, [])
```
There are other ways to only add the event listener once, depending on your use case.

**Comment by heokhe** [comment]
I just used `once` as an example, but thanks anyway!

**Comment by srmagura** [comment]
Going to leave this open and pin it until `addEventListener` options are added to this repo ;)

**Comment by donavon** [comment]
deployed to npm as `@use-it/event-listener@0.1.4`
